import React from "react";
import { graphql, useStaticQuery, Link } from "gatsby";
import { Box, Heading, Text, Button } from "rebass/styled-components";
import Img from "gatsby-image";
import PropTypes from "prop-types";
import Nav from "./Nav";
import Container from "./Container";

/** A simple header component which contains the navigation, a background image, section for header text */
const Header = ({
  title,
  subTitle,
  navBackground,
  image,
  category,
  includeCTA,
  navtop
}) => {
  const data = useStaticQuery(graphql`
    query imgQuery {
      file(relativePath: { eq: "headerImageDefault.jpg" }) {
        childImageSharp {
          # Specify the image processing specifications right in the query.
          # Makes it trivial to update as your page's design changes.
          fluid(maxWidth: 2000) {
            ...GatsbyImageSharpFluid
          }
        }
      }
    }
  `);

  return (
    <>
      {!navtop && <Nav bg="primary" p={0} />}
      <Box as="header" bg="primary" sx={{ position: "relative" }}>
        <Img
          fluid={image.fluid || data.file.childImageSharp.fluid}
          alt={image.alt || title}
          style={{
            position: "absolute",
            left: 0,
            top: 0,
            width: "100%",
            height: "100%",
            overflow: "hidden"
          }}
        />
        {navtop && <Nav bg={navBackground} />}
        <Container>
          <Box
            sx={{ position: "relative" }}
            py={[3, 5]}
            px={3}
            color="white"
            minHeight={[0, 300]}
            width={[1, 1 / 2]}
          >
            <Text
              color="primary"
              fontFamily="subheading"
              mb="2"
              fontSize={[4]}
              sx={{ textTransform: "uppercase" }}
            >
              {category}
            </Text>
            <Heading
              as="h1"
              fontSize={[6, 6, 7]}
              mb="1.4rem"
              sx={{ textTransform: "uppercase" }}
            >
              {title}
            </Heading>
            <Text as="p" fontSize={[4, 4, 5]}>
              {subTitle}
            </Text>
            {includeCTA && (
              <Link to="/appointment">
                <Button mt={3} variant="primary" minWidth={["100%", "100%", 0]}>
                  Book a free appointment
                </Button>
                <Button
                  ml={[0, 0, 2]}
                  mt={3}
                  variant="ghost"
                  minWidth={["100%", "100%", 0]}
                >
                  Why Century21
                </Button>
              </Link>
            )}
          </Box>
        </Container>
      </Box>
    </>
  );
};

Header.propTypes = {
  /** Generated by datocms. Typical usage would be the page title */
  title: PropTypes.string.isRequired,
  /** Generated by datocms. Typical usage would be a subtitle. */
  subTitle: PropTypes.string,
  /** Generated by datocms. If blank uses a default image*/
  backgroundImage: PropTypes.string,
  /** If true places navigation above the header image with a solid background rather than inside with a transparent background */
  navtop: PropTypes.bool
};

Header.defaultProps = {
  image: {}
};
export default Header;
